### ISSUE TITLE
网卡问题

### ISSUE THREAD

**Issue by hlla** [jdjxk/Hackintosh_OpenCore_Z490_i9_10850K_RX6600XT#1]
大佬，MSI Z490-S01是直接安装BCM943602CDP还是转pcie的

**Comment by jdjxk** [comment]
PCIE 转接卡

**Comment by hlla** [comment]
谢谢大佬，有链接推荐吗，关键字也行，淘宝上搜不到CDP的

**Comment by jdjxk** [comment]
只能去找二手的，而且价格炒得很高，其实奋威T919也不错，我换了CDP没有明显提升。
