### ISSUE TITLE
MSI Z490M-S01这主板可以用您的EFI么？

### ISSUE THREAD

**Issue by birkh8792** [jdjxk/Hackintosh_OpenCore_Z490_i9_10850K_RX6600XT#3]
MSI Z490M-S01这主板可以用您的EFI么？

**Comment by jdjxk** [comment]
可以的，USB端口可能需要自己重新定制下，其他应该不会有大的区别。

**Comment by lanjd** [comment]
> MSI Z490M-S01这主板可以用您的EFI么？

兄弟 MSI Z490M-S01 你驱动了么，我也是这块主板，不知道能不能抄作业
